[cheat_set]
; Enable or disable the entire plugin (1 = enabled, 0 = disabled)
enabled=1

; Enable cheat menu by writing directly to memory at offset 0x9D4F18 (1 = enabled, 0 = disabled)
memory_patch=1

; Automatically send C+H+E keystrokes after map load (1 = enabled, 0 = disabled)
; Currently serves as a fallback if memory_patch doesn't work.
auto_keys=0

; ==============================================================================
; Cheat Functions (1 = enabled, 0 = disabled)
; ==============================================================================

; Group 1
speed_up_construction=0
speed_up_research=0
speed_up_vehicle_production=0
speed_up_growing_trees=0

; Group 2
speed_up_pollution=0
speed_up_wear_and_tear=0
experimental_traffic_pathfinding=0
train_route_signal=1
